name: salonen
favicon: null
layout_spectrum: 0.75374
typography_spectrum: 0.8506264647003263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d9d4'
    - '#8f8a86'
    - '#23242d'
    - '#96bec0'
    - '#5a463b'
  brandStrength: 0.8125
  lightness: 0.9727258589118719
  saturation: 0.5592619408853352
  rhythmicContrast: 0.444236000534147
purpose: []
